version: '3'

services:

  mysql-local:
    image: mysql/mysql-server:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=urlschema
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306
      
  myapp-main:
    build:
      context: .
      dockerfile: Dockerfile
    image: restapi
    restart: on-failure
    depends_on:
        - mysql-local
    ports:
      - 8080:8080
      
  frontend:
    image: urlrestui
    ports:
      - "3000:3000"
    depends_on:
      - myapp-main
      